### ISSUE TITLE
Is the thermalProperties yet to be finished?

### ISSUE THREAD

**Issue by shepherdChua** [Franjcf/hybridBiotInterFoam#2]
Hi there! 
I saw that there is a dictionary about reading the thermal properties at the directory of solvers. But I didn't see any related equations in the *.C file and the thermalProperties in the constant directory have no influence on the simulation result. So I am just wondering is this the part yet to be finished or I just missed anything? 
And thantk you!

**Comment by Franjcf** [comment]
Hi! 

Thanks for your question. If I am not mistaken, the solver should be able to react to changes in the thermal properties dictionary, but only if you define an appropriate temperature field (I did not do this because everything I did in the related paper was in isothermal conditions).

The reference to the thermalDictionary is in  the "createSolidMechFields.H" file. I kept it there to ensure its compatibility with cases set up with OpenFOAM's elastic solver, but did not test its capabilities. I see now how this can be confusing. 

Unfortunately, I am not currently planning on expanding (and testing) the solver for non-isothermal conditions. However, I think this particular expansion should work with the addition described above. 

Best,
Francisco

**Comment by Shi-Feng** [comment]
Hi, Franjcf!
An excellent work. I am very interested in it. I wonder if elastoplastic constitutive models for porous media, such as the Mohr-Coulomb model, can be easily implemented into the toolbox? 
Thanks so much!

**Comment by Franjcf** [comment]
Hi Shi-Feng,

Great question. Unfortunately, I am not very familiar with the implementation of elastoplastic models, so I cannot comment on the potential difficulty of their implementation. However, as long as you can define a proper PDE that fits into the general form of eqn. 29 in the related paper (Modeling Multiphase Flow Within and Around Deformable Porous Materials: A Darcy Brinkman-Biot Approach), the solver should work as advertised.
